const router = require('express').Router()
const userRouter = require('./user.routers')
const installmentRouter = require('./installment.routers')
const invoiceRouter = require('./invoice.routers')
const paymentRouter = require('./payment.routers')
router.use('/users', userRouter)
router.use('/installments', installmentRouter)
router.use('/invoices', invoiceRouter)
router.use('/payments', paymentRouter)
module.exports = router
